AllCops:
  Exclude:
    - bin/rails
    - bin/spring
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - namespace

Metrics/LineLength:
  Max: 120
